"""Add trees.enabled

Revision ID: 22c8d1fba959
Revises: 66e56620891a
Create Date: 2023-06-19 15:31:06.235185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c8d1fba959'
down_revision = '66e56620891a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trees', sa.Column('enabled', sa.Integer(), server_default='1', nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trees', 'enabled')
    # ### end Alembic commands ###
