"""Add tree column to User

Revision ID: e176543c72a8
Revises: e5e738d09fa7
Create Date: 2023-03-13 13:37:40.620127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e176543c72a8'
down_revision = 'e5e738d09fa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tree', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_tree'), 'users', ['tree'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_tree'), table_name='users')
    op.drop_column('users', 'tree')
    # ### end Alembic commands ###
